eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
microservices:
  payment-service:
    endpoints:
      fetchByPaymentId:
        uri: http://PAYMENT-SERVICE/payments"

  user-service:
    endpoints:
      fetchByUserId:
        uri: http://USER-SERVICE/users
test:
  id: 10
